// <auto-generated />
using System;
using HT.P1.Jwt_Swagger.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HT.P1.Jwt_Swagger.Migrations
{
    [DbContext(typeof(JdDbContext))]
    [Migration("20191224074001_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HT.P1.Jwt_Swagger.Models.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BuyTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HomeId")
                        .HasColumnType("int");

                    b.Property<int>("Shape")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Desk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyTime = new DateTime(2016, 9, 7, 15, 40, 1, 6, DateTimeKind.Local).AddTicks(6531),
                            Cost = 600.0,
                            CreateTime = new DateTime(2019, 12, 24, 15, 40, 1, 5, DateTimeKind.Local).AddTicks(5938),
                            HomeId = 1,
                            Shape = 1
                        },
                        new
                        {
                            Id = 2,
                            BuyTime = new DateTime(2018, 3, 17, 15, 40, 1, 7, DateTimeKind.Local).AddTicks(495),
                            Cost = 123.5,
                            CreateTime = new DateTime(2019, 12, 24, 15, 40, 1, 7, DateTimeKind.Local).AddTicks(347),
                            HomeId = 1,
                            Shape = 2
                        });
                });

            modelBuilder.Entity("HT.P1.Jwt_Swagger.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Home");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "武汉市东湖高新区",
                            Age = 3,
                            CreateTime = new DateTime(2019, 12, 24, 15, 40, 0, 999, DateTimeKind.Local).AddTicks(2940),
                            HostName = "华天晓",
                            Lat = 123.12,
                            Lng = 31.234556000000001
                        });
                });

            modelBuilder.Entity("HT.P1.Jwt_Swagger.Models.Desk", b =>
                {
                    b.HasOne("HT.P1.Jwt_Swagger.Models.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId");
                });
#pragma warning restore 612, 618
        }
    }
}
